### ISSUE TITLE
knife download fails - Error: chef_server_root_dir.rb:26:in `<top (required)>'

### ISSUE THREAD

**Issue by cbanciu667** [jkeiser/knife-essentials#113]
knife download is not working, all required gems installed, fresh ubuntu installation with only chefdk and python
 user@devmachine:  ~/cookbooks:  knife download data_bags -VV    
INFO: Using configuration from /home/user1/.chef/knife.rb
/opt/chefdk/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:120:in `require': cannot load such file -- chef/rest (LoadError)
    from /opt/chefdk/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:120:in `require'
    from /home/user1/.chefdk/gem/ruby/2.4.0/gems/knife-essentials-1.5.6/lib/chef_fs/file_system/chef_server_root_dir.rb:26:in `<top (required)>'
    from /opt/chefdk/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
    from /opt/chefdk/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
    from /home/user1/.chefdk/gem/ruby/2.4.0/gems/knife-essentials-1.5.6/lib/chef_fs/config.rb:45:in `create_chef_fs'
    from /home/user1/.chefdk/gem/ruby/2.4.0/gems/knife-essentials-1.5.6/lib/chef_fs/config.rb:41:in `chef_fs'
    from /home/user1/.chefdk/gem/ruby/2.4.0/gems/knife-essentials-1.5.6/lib/chef_fs/knife.rb:83:in `chef_fs'
    from /home/user1/.chefdk/gem/ruby/2.4.0/gems/knife-essentials-1.5.6/lib/chef/knife/download_essentials.rb:58:in `block in run'
    from /home/user1/.chefdk/gem/ruby/2.4.0/gems/knife-essentials-1.5.6/lib/chef/knife/download_essentials.rb:57:in `each'
    from /home/user1/.chefdk/gem/ruby/2.4.0/gems/knife-essentials-1.5.6/lib/chef/knife/download_essentials.rb:57:in `run'
    from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/knife.rb:442:in `block in run_with_pretty_exceptions'
    from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/local_mode.rb:44:in `with_server_connectivity'
    from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/knife.rb:441:in `run_with_pretty_exceptions'
    from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/knife.rb:219:in `run'
    from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/application/knife.rb:156:in `run'
    from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/bin/knife:25:in `<top (required)>'
    from /opt/chefdk/bin/knife:267:in `load'
    from /opt/chefdk/bin/knife:267:in `<main>'

uname -a
Linux devmachine 4.10.0-37-generic #41-Ubuntu SMP Fri Oct 6 20:20:37 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]

sudo lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 17.04
Release:    17.04
Codename:   zesty

latest chef/CHEFDK(v13) for Ubuntu

**Comment by cbanciu667** [comment]
Chef Development Kit Version: 2.3.4
chef-client version: 13.4.19
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.17.0
inspec version: 1.36.1

RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.13
  - RUBY VERSION: 2.4.2 (2017-09-14 patchlevel 198) [x86_64-linux]
  - INSTALLATION DIRECTORY: /home/user1/.chefdk/gem/ruby/2.4.0
  - USER INSTALLATION DIRECTORY: /home/user1/.chefdk/gem/ruby/2.4.0
  - RUBY EXECUTABLE: /opt/chefdk/embedded/bin/ruby
  - EXECUTABLE DIRECTORY: /home/user1/.chefdk/gem/ruby/2.4.0/bin
  - SPEC CACHE DIRECTORY: /home/user1/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /opt/chefdk/embedded/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /home/user1/.chefdk/gem/ruby/2.4.0
     - /opt/chefdk/embedded/lib/ruby/gems/2.4.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "install" => "--user --no-document"
     - "update" => "--user --no-document"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /opt/chefdk/bin
     - /home/user1/.chefdk/gem/ruby/2.4.0/bin
     - /opt/chefdk/embedded/bin
     - /home/user1/.chefdk/gem/ruby/2.4.0/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /usr/games
     - /usr/local/games
     - /snap/bin
     - /opt/chefdk/gitbin

**Comment by cbanciu667** [comment]
and that is why chef will die... slow issue solving.... l already my experience with knife block...

**Comment by cbanciu667** [comment]
ok i will try to use version 2.3.0 because it works and ignore any progress here... no response for one day is too much fir this critical part of 'knife download'
